name: Deploy to Function App

on:
  push:
    branches: ["main"]

env:
  AZURE_FUNCTIONAPP_NAME: 'ccdeproject-api'     
  AZURE_RESOURCE_GROUP: CCDE-Project 
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'CCDE-PortfolioApp\PortfolioApi'    
  DOTNET_VERSION: '8.0.x'                                 

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:                 
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Publish function project
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet publish --configuration Release --output ./publish --no-self-contained
          popd

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Function App settings    
        shell: pwsh
        run: |
          az functionapp config appsettings set `
            --name "$env:AZURE_FUNCTIONAPP_NAME" `
            --resource-group "$env:AZURE_RESOURCE_GROUP" `
            --settings `
              COSMOSDB_CONNECTION_STRING=$env:COSMOSDB_CONNECTION_STRING `
              COSMOS_DATABASE_ID=$env:COSMOSDB_DATABASE_ID `
              COSMOS_CONTAINER_ID=$env:COSMOSDB_CONTAINER_ID
        env:
          COSMOSDB_CONNECTION_STRING: ${{ secrets.COSMOSDB_CONNECTION_STRING }}
          COSMOSDB_DATABASE_ID: ${{ vars.COSMOS_DATABASE_ID }}
          COSMOSDB_CONTAINER_ID: ${{ vars.COSMOS_CONTAINER_ID }} 

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/publish'
          sku: 'flexconsumption'
          remote-build: false            